<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting' => '<strong>确认</strong> 删除',
    'Add Task' => '增加任务',
    'Cancel' => '取消',
    'Delete' => '删除',
    'Do you really want to delete this task?' => '你真的要删除此任务吗？',
    'No open tasks...' => '没有打开的任务...',
    'completed tasks' => '完成任务',
    'Edit Task' => '编辑任务',
];
